#!/usr/bin/bash

sudo xbps-install -Suy
sudo xbps-install -Sy void-repo-nonfree
sudo xbps-install -S
sudo xbps-install -Sy xorg-minimal mesa-intel-dri xf86-video-intel i3 i3lock i3status dmenu polybar nano geany terminator xinit dejavu-fonts-ttf firefox-i18n-pt-BR 
sudo xbps-install -Sy lxappearance xdotool yad jq xbacklight rofi cmus Adapta papirus-icon-theme breeze-cursors pulseaudio pavucontrol 
sudo xbps-install -Sy libnotify lxrandr lxappearance xarchiver mpv gmtp feh gvfs-mtp mtpfs atool highlight poppler-utils mupdf 
sudo xbps-install -Sy transmission neofetch git xsel rxvt-unicode conky compton pcmanfm curl dunst alsa-utils
sudo xbps-install -Sy font-firacode unzip zip libyaml-devel libffi-devel zlib-devel readline-devel gcc make docker docker-compose vscode nodejs yarn 
sudo xbps-install -Sy ranger xrdb cgmanager polkit ConsoleKit2 ntfs-3g xfce-polkit elogind udisks2 setxkbmap wicd

##wifi wicd
 
sudo usermod -aG users $USER

sudo rm -fr /var/service/dhcpcd
sudo rm -fr /var/service/wpa_supplicant

sudo ln -s /etc/sv/wicd /var/service
sudo ln -s /etc/sv/dbus /var/service

sudo sv start dbus
sudo sv start wicd

sudo usermod -a -G pulse-access $USER
##docker run

sudo ln -s /etc/sv/docker /var/service/
sudo usermod -aG docker $USER
sudo sv start docker

##other services

sudo ln -s /etc/sv/cgmanager /var/service/
sudo ln -s /etc/sv/consolekit /var/service/
sudo ln -s /etc/sv/polkitd /var/service/

sudo sv start cgmanager
sudo sv start consolekit
sudo sv start polkitd

##font MS

#git clone https://github.com/void-linux/void-packages.git
#cd void-packages
#./xbps-src binary-bootstrap
#echo 'XBPS_ALLOW_RESTRICTED=yes' >> etc/conf
#./xbps-src pkg msttcorefonts
#sudo xbps-install -Ry hostdir/binpkgs/nonfree msttcorefonts
