#!/usr/bin/bash

sudo xbps-install -Suy
sudo xbps-install -Sy void-repo-nonfree void-repo-multilib
sudo xbps-install -S
sudo xbps-install -Sy xorg-minimal mesa-intel-dri xf86-video-intel i3 i3lock i3status dmenu nano geany terminator xinit dejavu-fonts-ttf firefox-i18n-pt-BR 
sudo xbps-install -Sy lxappearance xset trash-cli xdotool yad jq xbacklight rofi cmus Adapta papirus-icon-theme breeze-cursors pulseaudio pavucontrol 
sudo xbps-install -Sy gcc-multilib openjdk libnotify lxrandr lxappearance xarchiver mpv gmtp feh gvfs-mtp mtpfs atool highlight poppler-utils mupdf 
sudo xbps-install -Sy transmission neofetch git xsel rxvt-unicode conky picom unar Thunar thunar-volman thunar-archive-plugin thunar-media-tags-plugin curl dunst alsa-plugins-pulseaudio alsa-utils
sudo xbps-install -Sy font-firacode rpmextract	lzip lrzip unzip zip libyaml-devel libffi-devel zlib-devel readline-devel gcc make docker docker-compose vscode yarn 
sudo xbps-install -Sy ranger sharutils squashfs-tools xrdb ntfs-3g elogind polkit-elogind polkit xfce-polkit dbus-elogind udisks2 setxkbmap  linux-firmware-intel  intel-ucode cbatticon-gtk3 wicd 
sudo xbps-reconfigure -f linux

xfconf-query --channel thunar --property /misc-exec-shell-scripts-by-default --create --type bool --set true

#polybar elogind  ConsoleKit2 polkit-elogind  polkit cgmanager

##wifi wicd
 
sudo usermod -aG users $USER

sudo rm -fr /var/service/dhcpcd
sudo rm -fr /var/service/wpa_supplicant

sudo ln -s /etc/sv/wicd /var/service
sudo ln -s /etc/sv/dbus /var/service

# sudo sv start dbus
sudo sv start wicd

sudo usermod -a -G pulse-access $USER
##docker run

sudo ln -s /etc/sv/docker /var/service/
sudo usermod -aG docker $USER
sudo sv start docker

##other services

#sudo ln -s /etc/sv/cgmanager /var/service/
# sudo ln -s /etc/sv/consolekit /var/service/
# sudo ln -s /etc/sv/polkitd /var/service/

#sudo sv start cgmanager
# sudo sv start consolekit
# sudo sv start polkitd

##font MS

#git clone https://github.com/void-linux/void-packages.git
#cd void-packages
#./xbps-src binary-bootstrap
#echo 'XBPS_ALLOW_RESTRICTED=yes' >> etc/conf
#./xbps-src pkg msttcorefonts
#sudo xbps-install -Ry hostdir/binpkgs/nonfree msttcorefonts
