#!/bin/bash 


# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  rofi -lines 12 -padding 18 -width 60 -location 0 -show drun -sidebar-mode -columns 3 -font 'Noto Sans 10' -show-icons -drun-icon-theme Papirus
 
# Right click
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
 rofi -lines 12 -padding 18 -width 60 -location 0 -show drun -sidebar-mode -columns 3 -font 'Noto Sans 10' -show-icons -drun-icon-theme Papirus
fi

killall rofi
