#!/bin/bash -

#ACTIVE_WINDOW=$(xprop -id $(xprop -root _NET_ACTIVE_WINDOW | cut -d ' ' -f 5) WM_NAME | cut -d '"' -f 2)

#if [[ "${ACTIVE_WINDOW}" != "" ]]; then
#  echo "${ACTIVE_WINDOW}"
#  echo "${ACTIVE_WINDOW}"
#  echo ""
#fi

if [[ "$(xdotool getactivewindow getwindowname)" != "$TITLE" ]]; then
    TITLE="$(xdotool getactivewindow getwindowname 2>/dev/null)"
	echo "${TITLE}"
#  echo "${TITLE}"
#  echo ""
else
	echo "i3"	
fi
